---
- name: Remove legacy Push VM Manifest job template from AAP
  awx.awx.job_template:
    name: "{{ aap_vm_pipeline_legacy_jt_push_vm }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    state: absent
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"

- name: Remove legacy Sync Infrastructure VMs job template from AAP
  awx.awx.job_template:
    name: "{{ aap_vm_pipeline_legacy_jt_sync_vms }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    state: absent
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"

- name: Remove standalone Provision VM workflow from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_vm_pipeline_legacy_workflow }}"
    organization: "{{ aap_vm_pipeline_organization }}"
    state: absent
    controller_host: "{{ aap_vm_pipeline_controller_host }}"
    controller_oauthtoken: "{{ aap_vm_pipeline_controller_oauthtoken }}"
    validate_certs: "{{ aap_vm_pipeline_validate_certs }}"
