apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: observability-prometheus
  namespace: "{{ observability.namespace }}"
spec:
  targetNamespaces:
    - "{{ observability.namespace }}"
