- name: Installation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Setup kubeconfig file
      ansible.builtin.include_role:
        name: demos.utils.kubeconfig

    - name: Install OpenShift MCP
      ansible.builtin.include_tasks:
        file: components/openshift-mcp/install.yaml

    - name: Install agent
      ansible.builtin.include_tasks:
        file: components/agent/install.yaml

    - name: Install chat
      ansible.builtin.include_tasks:
        file: components/chat/install.yaml

    - name: Install monitor
      ansible.builtin.include_tasks:
        file: components/monitor/install.yaml

  vars_files:
    - vars.yaml
