- name: Installation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Setup kubeconfig file
      ansible.builtin.include_role:
        name: demos.utils.kubeconfig

    - name: Install OpenShift MCP
      ansible.builtin.include_tasks:
        file: components/openshift-mcp/install.yaml

    - name: Install AAP MCP
      ansible.builtin.include_tasks:
        file: components/aap-mcp/install.yaml

    - name: Install AAP EDA
      ansible.builtin.include_tasks:
        file: components/aap-eda/install.yaml

    - name: Install ITSM
      ansible.builtin.include_tasks:
        file: components/itsm/install.yaml

    - name: Install Gitea
      ansible.builtin.include_tasks:
        file: components/gitea/install.yaml

    - name: Install observability
      ansible.builtin.include_tasks:
        file: components/observability/install.yaml

    - name: Install agent
      ansible.builtin.include_tasks:
        file: components/agent/install.yaml

    - name: Install chat
      ansible.builtin.include_tasks:
        file: components/chat/install.yaml

    - name: Install monitor
      ansible.builtin.include_tasks:
        file: components/monitor/install.yaml

  vars_files:
    - vars.yaml

- import_playbook: components/aap-casc/deploy/playbooks/casc/install.yml
