---
- name: Uninstallation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Setup kubeconfig file
      ansible.builtin.include_role:
        name: demos.utils.kubeconfig

    - name: Uninstall OpenShift MCP
      ansible.builtin.include_tasks:
        file: components/openshift-mcp/uninstall.yaml

  vars_files:
    - vars.yaml
