---
- name: Uninstallation
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Ensure OpenShift API access is available
      ansible.builtin.include_tasks:
        file: components/aap-casc/deploy/playbooks/casc/tasks/ensure_openshift_access.yml

    - name: Uninstall AAP CASC
      ansible.builtin.include_tasks:
        file: components/aap-casc/deploy/playbooks/casc/uninstall-tasks.yml

    - name: Uninstall monitor
      ansible.builtin.include_tasks:
        file: components/monitor/uninstall.yaml

    - name: Uninstall observability
      ansible.builtin.include_tasks:
        file: components/observability/uninstall.yaml

    - name: Uninstall chat
      ansible.builtin.include_tasks:
        file: components/chat/uninstall.yaml

    - name: Uninstall agent
      ansible.builtin.include_tasks:
        file: components/agent/uninstall.yaml

    - name: Uninstall Gitea
      ansible.builtin.include_tasks:
        file: components/gitea/uninstall.yaml

    - name: Uninstall ITSM
      ansible.builtin.include_tasks:
        file: components/itsm/uninstall.yaml

  vars_files:
    - vars.yaml
