apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: "{{ observability.namespace }}"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: "{{ observability.part_of_label }}"
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
