---
- name: Remove Resolve ITSM Change from Request job template from AAP
  awx.awx.job_template:
    name: "{{ aap_apache_stack_pipeline_jt_resolve_itsm_change }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"

- name: Remove Generic Application stack job templates from AAP
  awx.awx.job_template:
    name: "{{ item }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop:
    - "{{ aap_vm_pipeline_jt_provision_vm }}"
    - "{{ aap_vm_pipeline_jt_register_itsm }}"
    - "{{ aap_httpd_pipeline_jt_configure }}"
    - "{{ aap_httpd_pipeline_jt_complete_stack }}"
    - "{{ aap_httpd_pipeline_jt_expose }}"
    - "{{ aap_httpd_pipeline_jt_register_itsm }}"

- name: Remove legacy granular job templates from AAP
  awx.awx.job_template:
    name: "{{ item }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop: "{{ aap_uninstall_legacy_job_templates }}"

- name: Remove Apache troubleshoot pipeline job templates from AAP
  awx.awx.job_template:
    name: "{{ item }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop:
    - "{{ aap_apache_troubleshoot_pipeline_jt_create_incident }}"
    - "{{ aap_apache_troubleshoot_pipeline_jt_troubleshoot }}"

- name: Remove Reset job template from AAP
  awx.awx.job_template:
    name: "{{ aap_reset_pipeline_jt_name }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  ignore_errors: true
