---
- name: Remove Deploy Generic Application Stack master workflow from AAP
  awx.awx.workflow_job_template:
    name: "{{ aap_apache_stack_pipeline_workflow }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"

- name: Remove legacy standalone workflows from AAP
  awx.awx.workflow_job_template:
    name: "{{ item }}"
    organization: "{{ aap_uninstall_organization }}"
    state: absent
    controller_host: "{{ aap_uninstall_controller_host }}"
    controller_oauthtoken: "{{ aap_uninstall_controller_oauthtoken }}"
    validate_certs: "{{ aap_uninstall_validate_certs }}"
  loop: "{{ aap_uninstall_legacy_workflows }}"
