apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrape-config
  namespace: "{{ observability.namespace }}"
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: "{{ observability.part_of_label }}"
stringData:
  prometheus-additional.yaml: |
    - job_name: kubevirt-vmi
      scheme: https
      tls_config:
        insecure_skip_verify: true
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - openshift-cnv
      relabel_configs:
        - action: keep
          source_labels: [__meta_kubernetes_service_label_prometheus_kubevirt_io]
          regex: "true"
        - action: keep
          source_labels: [__meta_kubernetes_endpoint_port_name]
          regex: metrics
