apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: "{{ observability.namespace }}"
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: "{{ observability.part_of_label }}"
spec:
  selector:
    matchLabels:
      operated-alertmanager: "true"
  endpoints:
    - port: web
      interval: 30s
      path: /metrics
